Repository apple/swift-crypto, pull requests merged in 2023-08, with the labels that each got.

#191 Backport: Add API providing basic RSA pubkey encrypt and privkey decrypt (#125)
  Sources/CCryptoBoringSSLShims/include/CCryptoBoringSSLShims.h
  Sources/CCryptoBoringSSLShims/shims.c
  Sources/_CryptoExtras/ChaCha20CTR/BoringSSL/ChaCha20CTR_boring.swift
  Sources/_CryptoExtras/RSA/RSA.swift
  Sources/_CryptoExtras/RSA/RSA_boring.swift
  Sources/_CryptoExtras/RSA/RSA_security.swift
  Tests/CryptoTests/Utils/XCTestUtils.swift
  Tests/_CryptoExtrasTests/TestRSAEncryption.swift
  Tests/_CryptoExtrasTests/Utils/BytesUtil.swift
  Tests/_CryptoExtrasVectors/rsa_oaep_2048_sha1_mgf1sha1_test.json
  Tests/_CryptoExtrasVectors/rsa_oaep_misc_test.json
Labels: 🔼 needs-minor-version-bump

#194 Fix up flags used for Docker
  scripts/vendor-boringssl.sh
Labels: needs-no-version-bump

#197 Set missing Windows defines
  Package.swift
Labels: patch-version-bump-only

#198 Use `SecKeyGetBlockSize` instead of `kSecAttrKeySizeInBits`
  Sources/_CryptoExtras/RSA/RSA.swift
  Sources/_CryptoExtras/RSA/RSA_security.swift
Labels: patch-version-bump-only
