Repository apple/swift-crypto, pull requests merged in 2024-10, with the labels that each got.

#266 Add Equatable and Hashable conformance for CryptoKitError and CryptoKitASN1Error
  Sources/Crypto/CryptoKitErrors.swift
Labels: semver/minor

#268 Support loading RSAPSS public keys with parameters
  CMakeLists.txt
  Package.swift
  Sources/_CryptoExtras/CMakeLists.txt
  Sources/_CryptoExtras/RSA/RSA.swift
  Sources/_CryptoExtras/Util/SubjectPublicKeyInfo.swift
  Tests/_CryptoExtrasTests/TestRSASigning.swift
Labels: semver/patch

#271 Update BoringSSL to 76968bb3d53982560bcf08bcd0ba3e1865fe15cd
  Package.swift
  Sources/CCryptoBoringSSL/CMakeLists.txt
  Sources/CCryptoBoringSSL/crypto/bcm_support.h
  Sources/CCryptoBoringSSL/crypto/cipher_extra/e_tls.c
  Sources/CCryptoBoringSSL/crypto/crypto.c
  Sources/CCryptoBoringSSL/crypto/dsa/internal.h
  Sources/CCryptoBoringSSL/crypto/ec_extra/ec_asn1.c
  Sources/CCryptoBoringSSL/crypto/fipsmodule/bcm.c
  Sources/CCryptoBoringSSL/crypto/fipsmodule/bcm_interface.h
  Sources/CCryptoBoringSSL/crypto/fipsmodule/cipher/aead.c.inc
  Sources/CCryptoBoringSSL/crypto/fipsmodule/dh/internal.h
  Sources/CCryptoBoringSSL/crypto/fipsmodule/digest/digests.c.inc
  Sources/CCryptoBoringSSL/crypto/fipsmodule/ec/ec_key.c.inc
  Sources/CCryptoBoringSSL/crypto/fipsmodule/ecdh/ecdh.c.inc
  Sources/CCryptoBoringSSL/crypto/fipsmodule/ecdsa/ecdsa.c.inc
  Sources/CCryptoBoringSSL/crypto/fipsmodule/rand/rand.c.inc
  Sources/CCryptoBoringSSL/crypto/fipsmodule/rsa/padding.c.inc
  Sources/CCryptoBoringSSL/crypto/fipsmodule/rsa/rsa.c.inc
  Sources/CCryptoBoringSSL/crypto/fipsmodule/rsa/rsa_impl.c.inc
  Sources/CCryptoBoringSSL/crypto/fipsmodule/self_check/self_check.c.inc
  Sources/CCryptoBoringSSL/crypto/fipsmodule/sha/sha256.c.inc
  Sources/CCryptoBoringSSL/crypto/fipsmodule/sha/sha512.c.inc
  Sources/CCryptoBoringSSL/crypto/internal.h
  Sources/CCryptoBoringSSL/crypto/rsa_extra/rsa_extra.c
  Sources/CCryptoBoringSSL/crypto/sha/sha256.c
  Sources/CCryptoBoringSSL/crypto/sha/sha512.c
  Sources/CCryptoBoringSSL/crypto/slhdsa/address.h
  Sources/CCryptoBoringSSL/crypto/slhdsa/fors.c
  Sources/CCryptoBoringSSL/crypto/slhdsa/fors.h
  Sources/CCryptoBoringSSL/crypto/slhdsa/internal.h
  Sources/CCryptoBoringSSL/crypto/slhdsa/merkle.c
  Sources/CCryptoBoringSSL/crypto/slhdsa/merkle.h
  Sources/CCryptoBoringSSL/crypto/slhdsa/params.h
  Sources/CCryptoBoringSSL/crypto/slhdsa/slhdsa.c
  Sources/CCryptoBoringSSL/crypto/slhdsa/thash.c
  Sources/CCryptoBoringSSL/crypto/slhdsa/thash.h
  Sources/CCryptoBoringSSL/crypto/slhdsa/wots.c
  Sources/CCryptoBoringSSL/crypto/slhdsa/wots.h
  Sources/CCryptoBoringSSL/hash.txt
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_base.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_bcm_public.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_boringssl_prefix_symbols.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_boringssl_prefix_symbols_asm.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_crypto.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_dh.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_dsa.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_ec_key.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_rsa.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_sha.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_slhdsa.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_span.h
  Sources/CCryptoBoringSSL/include/boringssl_prefix_symbols_nasm.inc
  scripts/vendor-boringssl.sh
Labels: semver/patch

#265 Refactor and adopt package access to remove symlinked files
  CMakeLists.txt
  Package.swift
  Sources/Crypto/AEADs/AES/GCM/BoringSSL/AES-GCM_boring.swift
  Sources/Crypto/AEADs/ChachaPoly/BoringSSL/ChaChaPoly_boring.swift
  Sources/Crypto/CMakeLists.txt
  Sources/Crypto/Keys/EC/BoringSSL/EllipticCurvePoint_boring.swift
  Sources/Crypto/Keys/EC/BoringSSL/EllipticCurve_boring.swift
  Sources/Crypto/Keys/EC/BoringSSL/NISTCurvesKeys_boring.swift
  Sources/Crypto/Signatures/BoringSSL/ECDSASignature_boring.swift
  Sources/CryptoBoringWrapper/CMakeLists.txt
  Sources/CryptoBoringWrapper/CryptoKitErrors_boring.swift
  Sources/CryptoBoringWrapper/Util/ArbitraryPrecisionInteger_boring.swift
  Sources/CryptoBoringWrapper/Util/FiniteFieldArithmeticContext_boring.swift
  Sources/_CryptoExtras/AES/AES_GCM_SIV.swift
  Sources/_CryptoExtras/AES/Block Function.swift
  Sources/_CryptoExtras/AES/BoringSSL/AES_GCM_SIV_boring.swift
  Sources/_CryptoExtras/CMakeLists.txt
  Sources/_CryptoExtras/ChaCha20CTR/BoringSSL/ChaCha20CTR_boring.swift
  Sources/_CryptoExtras/ChaCha20CTR/ChaCha20CTR.swift
  Sources/_CryptoExtras/RSA/RSA+BlindSigning.swift
  Sources/_CryptoExtras/RSA/RSA.swift
  Sources/_CryptoExtras/RSA/RSA_boring.swift
  Sources/_CryptoExtras/Util/Shared
  Tests/CryptoBoringWrapperTests/ArbitraryPrecisionIntegerTests.swift
  Tests/CryptoBoringWrapperTests/FiniteFieldArithmeticTests.swift
  Tests/_CryptoExtrasTests/TestRSASigning.swift
Labels: semver/patch

#277 wrapper: Move EC types and random bytes into CryptoBoringWrapper
  Sources/Crypto/CMakeLists.txt
  Sources/CryptoBoringWrapper/CMakeLists.txt
  Sources/CryptoBoringWrapper/EC/EllipticCurve.swift
  Sources/CryptoBoringWrapper/EC/EllipticCurvePoint.swift
  Sources/CryptoBoringWrapper/Util/ArbitraryPrecisionInteger.swift
  Sources/CryptoBoringWrapper/Util/FiniteFieldArithmeticContext.swift
  Sources/CryptoBoringWrapper/Util/RandomBytes.swift
  Sources/_CryptoExtras/CMakeLists.txt
  Tests/CryptoBoringWrapperTests/ArbitraryPrecisionIntegerTests.swift
  Tests/CryptoBoringWrapperTests/FiniteFieldArithmeticTests.swift
Labels: semver/patch

#284 wrapper: Add modular arithmetic functions to ArbitraryPrecisionInteger
  Sources/CryptoBoringWrapper/Util/ArbitraryPrecisionInteger.swift
  Tests/CryptoBoringWrapperTests/ArbitraryPrecisionIntegerTests.swift
Labels: semver/patch

#279 Fix windows build and update BoringSSL to 2587c4974dbe9872451151c8e975f58567a1ce0d
  Package.swift
  Sources/CCryptoBoringSSL/crypto/bio/connect.c
  Sources/CCryptoBoringSSL/crypto/poly1305/poly1305_vec.c
  Sources/CCryptoBoringSSL/hash.txt
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_base.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_evp.h
  scripts/vendor-boringssl.sh
Labels: semver/patch

#98 New API Proposal: PBKDF2
  Sources/_CryptoExtras/CMakeLists.txt
  Sources/_CryptoExtras/Key Derivation/KDF.swift
  Sources/_CryptoExtras/Key Derivation/PBKDF2/BoringSSL/PBKDF2_boring.swift
  Sources/_CryptoExtras/Key Derivation/PBKDF2/BoringSSL/PBKDF2_commoncrypto.swift
  Sources/_CryptoExtras/Key Derivation/PBKDF2/PBKDF2.swift
  Sources/_CryptoExtras/Key Derivation/Scrypt/BoringSSL/Scrypt_boring.swift
  Sources/_CryptoExtras/Key Derivation/Scrypt/Scrypt.swift
  Tests/_CryptoExtrasTests/PBKDF2Tests.swift
  Tests/_CryptoExtrasTests/ScryptTests.swift
  Tests/_CryptoExtrasTests/Utils/RFCVector.swift
  Tests/_CryptoExtrasTests/Utils/XCTestUtils.swift
  Tests/_CryptoExtrasVectors/rfc-6070-PBKDF2-SHA1.txt
  Tests/_CryptoExtrasVectors/rfc-7914-scrypt.txt
Labels: semver/minor

#288 [CI] Enable Windows CI
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .github/workflows/scheduled.yml
Labels: semver/none

#291 Fix WASI platform build issue
  Sources/CryptoBoringWrapper/Util/RandomBytes.swift
Labels: semver/patch
