Repository apple/swift-crypto, pull requests merged in 2025-08, with the labels that each got.

#394 Add AES CMAC support
  Sources/_CryptoExtras/AES/CMAC.swift
  Sources/_CryptoExtras/CMakeLists.txt
  Tests/_CryptoExtrasTests/CMACTests.swift
  Tests/_CryptoExtrasTests/Utils/BytesUtil.swift
  Tests/_CryptoExtrasVectors/aes_cmac_test.json
Labels: 🆕 semver/minor

#396 Improve vendor-boringssl.sh script to make it work better
  Package.swift
  scripts/vendor-boringssl.sh
Labels: semver/none

#399 Use Swift SDKs to generate symbols for Linux targets and armv7 (using swift-sdk-generator)
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_boringssl_prefix_symbols.h
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL_boringssl_prefix_symbols_asm.h
  Sources/CCryptoBoringSSL/include/boringssl_prefix_symbols_nasm.inc
  scripts/generate-linux-sdks.sh
  scripts/vendor-boringssl.sh
Labels: semver/none

#402 Avoid TSAN issue in _CryptoExtras/AES/CMAC
  Sources/_CryptoExtras/AES/CMAC.swift
Labels: 🔨 semver/patch
