Repository apple/swift-crypto, pull requests merged in 2025-04, with the labels that each got.

#347 Enable macOS CI on pull requests
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#346 perf: Add benchmarks and reduce allocations by ~50% for ARC and VOPRF
  Benchmarks/Benchmarks/Benchmarks.swift
  Benchmarks/Package.swift
  Sources/CryptoBoringWrapper/EC/EllipticCurve.swift
  Sources/CryptoBoringWrapper/EC/EllipticCurvePoint.swift
  Sources/CryptoBoringWrapper/Util/FiniteFieldArithmeticContext.swift
  Sources/_CryptoExtras/CMakeLists.txt
  Sources/_CryptoExtras/ECToolbox/BoringSSL/ECToolbox_boring.swift
  Sources/_CryptoExtras/Util/Data+Extensions.swift
Labels: 🔨 semver/patch

#350 Fix broken Windows tests
  Tests/CryptoTests/Utils/RFCVector.swift
  Tests/CryptoTests/Utils/Wycheproof.swift
  Tests/_CryptoExtrasTests/Utils/RFCVector.swift
  Tests/_CryptoExtrasTests/Utils/Wycheproof.swift
Labels: semver/none

#351 Enable Swift 6.1 jobs in CI
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#349 OpenBSD support.
  Package.swift
  Sources/CCryptoBoringSSL/CMakeLists.txt
  Sources/Crypto/CMakeLists.txt
  Sources/Crypto/Util/SecureBytes.swift
  Sources/CryptoBoringWrapper/Util/RandomBytes.swift
  Sources/_CryptoExtras/CMakeLists.txt
  Tests/CryptoTests/SecureBytes/SecureBytesTests.swift
Labels: 🆕 semver/minor

#267 Add ML-DSA post-quantum signatures to `_CryptoExtras`
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL.h
  Sources/_CryptoExtras/CMakeLists.txt
  Sources/_CryptoExtras/Docs.docc/index.md
  Sources/_CryptoExtras/MLDSA/MLDSA65_boring.swift
  Sources/_CryptoExtras/Util/Optional+withUnsafeBytes.swift
  Tests/_CryptoExtrasTests/MLDSA65Tests.swift
  Tests/_CryptoExtrasVectors/mldsa_65_nist_keygen_tests.json
  Tests/_CryptoExtrasVectors/mldsa_65_standard_verify_test.json
  scripts/vendor-boringssl.sh
Labels: 🆕 semver/minor

#314 Add ML-KEM post-quantum key agreement to `_CryptoExtras`
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL.h
  Sources/_CryptoExtras/CMakeLists.txt
  Sources/_CryptoExtras/MLKEM/MLKEM_boring.swift
  Sources/_CryptoExtras/MLKEM/MLKEM_boring.swift.gyb
  Tests/_CryptoExtrasTests/MLKEMTests.swift
  scripts/vendor-boringssl.sh
Labels: 🆕 semver/minor
