Repository apple/swift-crypto, pull requests merged in 2025-03, with the labels that each got.

#332 Rename nightly_6_1 params to nightly_next
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#333 Only apply standard swift settings on valid targets
  Package.swift
Labels: semver/none

#335 Add Sendable conformance to ARC API types
  Sources/_CryptoExtras/ARC/ARC+API.swift
Labels: 🆕 semver/minor

#337 Add missing availability guards required when development mode enabled
  Sources/Crypto/ASN1/ASN1.swift
  Sources/Crypto/ASN1/Basic ASN1 Types/ASN1BitString.swift
  Sources/Crypto/ASN1/Basic ASN1 Types/ASN1Identifier.swift
  Sources/Crypto/ASN1/Basic ASN1 Types/ASN1Integer.swift
  Sources/Crypto/ASN1/Basic ASN1 Types/ASN1OctetString.swift
  Sources/Crypto/ASN1/Basic ASN1 Types/ObjectIdentifier.swift
  Sources/Crypto/CryptoKitErrors.swift
  Sources/Crypto/HPKE/Ciphersuite/KEM/Conformances/HPKE-KEM-Curve25519.swift
  Sources/Crypto/Signatures/ECDSA.swift
  Sources/Crypto/Util/SecureBytes.swift
Labels: 🔨 semver/patch

#339 Fix availability mismatches
  Sources/_CryptoExtras/ARC/ARCEncoding.swift
  Sources/crypto-shasum/main.swift
Labels: 🔨 semver/patch

#342 Use centralized CMake checks
  .github/workflows/pull_request.yml
  CONTRIBUTING.md
  scripts/check-cmake-lists.sh
  scripts/update-cmake-lists.sh
Labels: semver/none

#343 CONTRIBUTING.md CMake checks docs tweaks
  CONTRIBUTING.md
Labels: semver/none

#345 Enable macOS CI on merge to main and daily timer
  .github/workflows/main.yml
Labels: semver/none
