Repository apple/swift-crypto, pull requests merged in 2025-07, with the labels that each got.

#373 Remove security backend
  .swiftformatignore
  Sources/_CryptoExtras/CMakeLists.txt
  Sources/_CryptoExtras/RSA/RSA.swift
  Sources/_CryptoExtras/RSA/RSA_security.swift
Labels: 🔨 semver/patch

#374 Add API for ARC(P-256) and deprecate ARC(P-384)
  Benchmarks/Benchmarks/Benchmarks.swift
  Sources/_CryptoExtras/ARC/ARC+API.swift
  Sources/_CryptoExtras/ARC/ARC.swift
  Sources/_CryptoExtras/ARC/ARCCredential.swift
  Sources/_CryptoExtras/ARC/ARCEncoding.swift
  Sources/_CryptoExtras/ARC/ARCPrecredential.swift
  Sources/_CryptoExtras/ARC/ARCPresentation.swift
  Sources/_CryptoExtras/ARC/ARCRequest.swift
  Sources/_CryptoExtras/ARC/ARCResponse.swift
  Sources/_CryptoExtras/ARC/ARCServer.swift
  Tests/_CryptoExtrasTests/ARC/ARCAPITests.swift
  Tests/_CryptoExtrasTests/ARC/ARCEncodingTests.swift
  Tests/_CryptoExtrasTests/ARC/ARCPublicAPITests.swift
  Tests/_CryptoExtrasTests/ARC/ARCTestVectors.swift
  Tests/_CryptoExtrasTests/ARC/ARCTests.swift
Labels: 🆕 semver/minor

#376 CMake: Declare ASN1 dependency
  cmake/modules/SwiftCryptoConfig.cmake.in
Labels: 🔨 semver/patch

#378 Mention Windows in README
  README.md
Labels: semver/none

#379 Back out changes post-quantum changes for release
  Sources/CCryptoBoringSSL/include/CCryptoBoringSSL.h
  Sources/_CryptoExtras/CMakeLists.txt
  Sources/_CryptoExtras/Docs.docc/index.md
  Sources/_CryptoExtras/MLDSA/MLDSA_boring.swift
  Sources/_CryptoExtras/MLDSA/MLDSA_boring.swift.gyb
  Sources/_CryptoExtras/MLKEM/MLKEM_boring.swift
  Sources/_CryptoExtras/MLKEM/MLKEM_boring.swift.gyb
  Sources/_CryptoExtras/Util/Optional+withUnsafeBytes.swift
  Tests/_CryptoExtrasTests/MLDSATests.swift
  Tests/_CryptoExtrasTests/MLKEMTests.swift
  Tests/_CryptoExtrasVectors/mldsa_65_verify_test.json
  Tests/_CryptoExtrasVectors/mldsa_87_verify_test.json
  Tests/_CryptoExtrasVectors/mldsa_nist_keygen_65_tests.json
  Tests/_CryptoExtrasVectors/mldsa_nist_keygen_87_tests.json
  scripts/vendor-boringssl.sh
Labels: 🆕 semver/minor

#370 build: Make swift-crypto build on Windows
  CMakeLists.txt
  Sources/CCryptoBoringSSL/CMakeLists.txt
Labels: 🔨 semver/patch

#386 Fix broken Windows tests (#350)
  Tests/CryptoTests/Utils/RFCVector.swift
  Tests/CryptoTests/Utils/Wycheproof.swift
  Tests/_CryptoExtrasTests/Utils/RFCVector.swift
  Tests/_CryptoExtrasTests/Utils/Wycheproof.swift
Labels: 🔨 semver/patch

#385 build: Make swift-crypto build on Windows
  CMakeLists.txt
  Sources/CCryptoBoringSSL/CMakeLists.txt
Labels: 🔨 semver/patch

#387 CMake Build: Disable CMP0157
  CMakeLists.txt
Labels: 🔨 semver/patch

#391 Cache curves to avoid repeatedly reallocating state
  Sources/Crypto/Keys/EC/BoringSSL/NISTCurvesKeys_boring.swift
Labels: 🔨 semver/patch

#392 Add Sequence conformance to AES._CBC.IV (#389)
  Sources/_CryptoExtras/AES/AES_CBC.swift
  Tests/_CryptoExtrasTests/AES_CBCTests.swift
Labels: 🆕 semver/minor
